-- Automation Alerts table (persisted alerts created by automation rules)
CREATE TABLE IF NOT EXISTS public.automation_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  type TEXT NOT NULL,
  priority TEXT NOT NULL,
  message TEXT NOT NULL,
  recommendation TEXT NULL,
  related_entity_id BIGINT NULL,
  related_entity_name TEXT NULL,
  rule_title TEXT NULL
);

-- RLS for development (adjust for production)
ALTER TABLE IF EXISTS public.automation_alerts ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY automation_alerts_select ON public.automation_alerts FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY automation_alerts_insert ON public.automation_alerts FOR INSERT WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY automation_alerts_update ON public.automation_alerts FOR UPDATE USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


