-- Automation Rules table for persisting rule definitions in Supabase
CREATE TABLE IF NOT EXISTS public.automation_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name TEXT NOT NULL,
  trigger TEXT NOT NULL,
  conditions JSONB NOT NULL DEFAULT '[]'::jsonb,
  actions JSONB NOT NULL DEFAULT '[]'::jsonb,
  enabled BOOLEAN NOT NULL DEFAULT TRUE
);

-- Basic RLS for development (adjust for production as needed)
ALTER TABLE IF EXISTS public.automation_rules ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY automation_rules_select ON public.automation_rules FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY automation_rules_insert ON public.automation_rules FOR INSERT WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY automation_rules_update ON public.automation_rules FOR UPDATE USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


