// Vercel Serverless Function: POST /api/send-report
// Sends an email with attachment via SendGrid using the payload generated by the CRM webhook delivery

export default async function handler(req: any, res: any) {
  // CORS (adjust origins as needed)
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, X-API-KEY');
  if (req.method === 'OPTIONS') return res.status(204).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const apiKey = process.env.SENDGRID_API_KEY;
  const fromEmail = process.env.FROM_EMAIL;
  const required = [apiKey, fromEmail];
  if (required.some(v => !v)) return res.status(500).json({ error: 'Server not configured (SENDGRID_API_KEY, FROM_EMAIL)' });

  try {
    const payload = req.body || {};
    // Expected shape (from CRM): { report: { name, recipients[] }, file: { filename, content_type, base64 }, stats }
    const report = payload.report || {};
    const file = payload.file || {};
    const recipients: string[] = Array.isArray(report.recipients) ? report.recipients : [];
    const overrideTo = process.env.TO_OVERRIDE; // optional force-to for testing

    if (!file?.base64 || !file?.filename || !file?.content_type) {
      return res.status(400).json({ error: 'Invalid file payload' });
    }
    const toList = overrideTo ? [overrideTo] : recipients;
    if (!toList.length) return res.status(400).json({ error: 'No recipients' });

    const subject = report?.name || 'CRM Report';
    const sgPayload = {
      personalizations: [{ to: toList.map((e: string) => ({ email: e })) }],
      from: { email: fromEmail },
      subject,
      content: [{ type: 'text/plain', value: `Attached: ${subject}` }],
      attachments: [{
        content: file.base64,
        filename: file.filename,
        type: file.content_type,
        disposition: 'attachment',
      }],
    };

    const sgRes = await fetch('https://api.sendgrid.com/v3/mail/send', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(sgPayload),
    });

    if (!sgRes.ok) {
      const text = await sgRes.text().catch(() => '');
      return res.status(sgRes.status).json({ error: text || 'SendGrid error' });
    }
    return res.status(200).json({ ok: true });
  } catch (e: any) {
    return res.status(500).json({ error: e?.message || 'Unexpected error' });
  }
}


